const {
    User,
    UserHobby,
    HobbySkill,
    UserSkill,
    PracticeSession,
    Conversation,
    Message,
    UserAsset,
    Hobby
} = require('../Models')

const {
    RESPONSE_TYPE,
    SKILL_LEVEL,
    USER_ASSET_PURPOSE,
    LEARNING_FORM
} = require('../Config/skillLearningConstants')

const { generateStructuredContent } = require('../Service/AiModelService')
const { sendResponse } = require('../Middleware/sendResponse')

// ─── Helpers: SVG Formatting ───────────────────────────────────────────────────

function escapeSvgText(value) {
    return String(value || '').replace(/[&<>'"]/g, character => ({
        '&': '&amp;',
        '<': '&lt;',
        '>': '&gt;',
        "'": '&apos;',
        '"': '&quot;'
    }[character]))
}

function getFallbackSvg(title = 'Skill Diagram') {
    const safeTitle = escapeSvgText(title)
    return `<svg width="400" height="150" viewBox="0 0 400 150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${safeTitle}">
  <title>${safeTitle}</title>
  <rect width="100%" height="100%" fill="#1e1e2e" rx="10"/>
  <text x="50%" y="40%" dominant-baseline="middle" text-anchor="middle" fill="#cba6f7" font-family="sans-serif" font-size="18" font-weight="bold">${safeTitle}</text>
  <text x="50%" y="65%" dominant-baseline="middle" text-anchor="middle" fill="#a6adc8" font-family="sans-serif" font-size="13">Visual guide generated for your practice session</text>
</svg>`
}

function cleanSvg(svgString, fallbackTitle = 'Skill Visual') {
    if (!svgString || typeof svgString !== 'string') {
        return getFallbackSvg(fallbackTitle)
    }

    let cleaned = svgString.trim()
    if (cleaned.includes('```xml')) {
        cleaned = cleaned.replace(/^```xml\s*/i, '').replace(/\s*```$/, '').trim()
    } else if (cleaned.includes('```svg')) {
        cleaned = cleaned.replace(/^```svg\s*/i, '').replace(/\s*```$/, '').trim()
    } else if (cleaned.includes('```')) {
        cleaned = cleaned.replace(/^```\s*/, '').replace(/\s*```$/, '').trim()
    }

    const svgMatch = cleaned.match(/<svg\b[^>]*>[\s\S]*<\/svg>/i)
    if (!svgMatch) return getFallbackSvg(fallbackTitle)

    cleaned = svgMatch[0].trim()
    const rootTag = cleaned.match(/^<svg\b[^>]*>/i)?.[0]
    const containsUnsafeContent = /<(?:script|foreignObject|iframe|object|embed|image|audio|video|style)\b|\son[a-z]+\s*=|\b(?:href|xlink:href)\s*=\s*(['"]?)\s*(?:https?:|\/\/|data:|javascript:)|url\s*\(\s*['"]?\s*(?:https?:|\/\/|data:|javascript:)/i.test(cleaned)

    if (!rootTag || !/\bviewBox\s*=/i.test(rootTag) || containsUnsafeContent) {
        console.warn('[SkillLearning] Rejected unsafe or incomplete SVG generated by AI.')
        return getFallbackSvg(fallbackTitle)
    }

    const safeTitle = escapeSvgText(fallbackTitle)
    cleaned = cleaned.replace(/^<svg\b([^>]*)>/i, (match, attributes) => {
        let safeAttributes = attributes
        if (!/\bxmlns\s*=/i.test(safeAttributes)) safeAttributes += ' xmlns="http://www.w3.org/2000/svg"'
        if (!/\brole\s*=/i.test(safeAttributes)) safeAttributes += ' role="img"'
        if (!/\baria-label\s*=/i.test(safeAttributes)) safeAttributes += ` aria-label="${safeTitle}"`
        return `<svg${safeAttributes}>`
    })

    if (!/<title\b/i.test(cleaned)) {
        cleaned = cleaned.replace(/^(<svg\b[^>]*>)/i, `$1<title>${safeTitle}</title>`)
    }

    return cleaned
}

// ─── Individual Form Processing Handlers ────────────────────────────────────────

function processTextForm(learningContent) {
    return learningContent.text || 'Here is your lesson for today.'
}

async function processSvgForm(learningContent, hobbySkill, userId, userHobbyId, assetIds) {
    if (!learningContent.svg) return null
    const validSvg = cleanSvg(learningContent.svg, hobbySkill?.name || 'Skill Visual')
    const svgAsset = await UserAsset.create({
        userId,
        userHobbyId,
        type: 'image',
        mimeType: 'image/svg+xml',
        purpose: USER_ASSET_PURPOSE.LEARNING_DIAGRAM,
        metadata: { svg: validSvg }
    })
    assetIds.push(svgAsset._id)
    return validSvg
}



function processQuizForm(learningContent) {
    if (!Array.isArray(learningContent.quiz) || learningContent.quiz.length === 0) return null
    return learningContent.quiz.map((q, idx) => ({
        id: q.id || `q_${idx + 1}`,
        question: q.question || 'Knowledge check question:',
        options: Array.isArray(q.options) ? q.options : [],
        correctIndex: typeof q.correctIndex === 'number' ? q.correctIndex : 0,
        explanation: q.explanation || ''
    }))
}

function processFlashcardsForm(learningContent) {
    const cards = learningContent.flashcards || learningContent.flashcard
    if (!Array.isArray(cards) || cards.length === 0) return null
    return cards.map(card => ({
        front: card.front || '',
        back: card.back || ''
    }))
}

function processMusicalNotesForm(learningContent) {
    if (!learningContent.musicalNotes || typeof learningContent.musicalNotes !== 'object') return null
    const mn = learningContent.musicalNotes
    return {
        instrument: mn.instrument || 'piano',
        bpm: Number.isFinite(mn.bpm) ? Math.max(20, Math.min(300, mn.bpm)) : 80,
        notes: Array.isArray(mn.notes)
            ? mn.notes.map(note => ({
                pitch: typeof note?.pitch === 'string' ? note.pitch : '',
                startBeat: Number.isFinite(note?.startBeat) ? Math.max(0, note.startBeat) : 0,
                durationBeats: Number.isFinite(note?.durationBeats) ? Math.max(0.125, note.durationBeats) : 1,
                velocity: Number.isFinite(note?.velocity) ? Math.max(0, Math.min(127, note.velocity)) : 80,
                finger: Number.isInteger(note?.finger) && note.finger >= 1 && note.finger <= 5 ? note.finger : null
            }))
            : []
    }
}

function processChecklistForm(learningContent) {
    if (!Array.isArray(learningContent.checklist) || learningContent.checklist.length === 0) return null
    return learningContent.checklist.map((item, idx) => ({
        step: item.step || idx + 1,
        title: item.title || `Step ${idx + 1}`,
        instruction: item.instruction || ''
    }))
}

function processVideoForm(learningContent) {
    if (!learningContent.video || typeof learningContent.video !== 'object') return null
    const v = learningContent.video
    return {
        title: v.title || 'Demonstration Video',
        embedUrl: v.embedUrl || '',
        startTimeSeconds: v.startTimeSeconds || 0,
        durationSeconds: v.durationSeconds || 30
    }
}

function processCodeSnippetForm(learningContent) {
    if (!learningContent.codeSnippet || typeof learningContent.codeSnippet !== 'object') return null
    const cs = learningContent.codeSnippet
    return {
        language: cs.language || 'python',
        code: cs.code || '',
        expectedOutput: cs.expectedOutput || ''
    }
}

// ─── Helper: AI-Driven Hobby & Skill Curriculum Generator ───────────────────────

async function detectAndCreateHobbyWithAi(userMessage, userId, modelChoice = 'gemini') {
    const aiSystemInstruction = `You are a Hobby & Skill Curriculum AI Architect.
Analyze the user's message and determine if the user is asking to learn a specific hobby or skill (e.g. Piano, Guitar, Sourdough Baking, Chess, Origami, Archery, French Cooking, Python Coding, Calligraphy, Skateboarding, Martial Arts, Songwriting).

If a specific hobby/skill is detected:
Return JSON:
{
  "isHobbyDetected": true,
  "hobbyName": "Proper Title Case Name",
  "slug": "url-friendly-slug",
  "category": "Broad Category (e.g. Music, Cooking, Sports, Creative, Gaming, Tech)",
  "description": "Brief 1-sentence description of the hobby.",
  "initialSkills": [
    {
      "name": "Skill Name 1",
      "slug": "skill-slug-1",
      "category": "Category",
      "skillType": "knowledge | physical | creative | technical | strategic",
      "description": "Short description"
    },
    {
      "name": "Skill Name 2",
      "slug": "skill-slug-2",
      "category": "Category",
      "skillType": "knowledge | physical | creative | technical | strategic",
      "description": "Short description"
    }
  ]
}

If NO specific hobby/skill is mentioned (e.g. "Hi", "Teach me something", "Hello", vague prompt):
Return JSON:
{
  "isHobbyDetected": false
}`

    try {
        const aiRes = await generateStructuredContent({
            model: modelChoice,
            systemInstruction: aiSystemInstruction,
            messages: [{ role: 'user', content: userMessage }],
            temperature: 0.2
        })

        if (!aiRes || !aiRes.isHobbyDetected || !aiRes.hobbyName) {
            return null
        }

        const slug = aiRes.slug || aiRes.hobbyName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')

        let hobby = await Hobby.findOne({ slug })
        if (!hobby) {
            hobby = await Hobby.create({
                name: aiRes.hobbyName,
                slug,
                category: aiRes.category || 'General',
                description: aiRes.description || `Learning ${aiRes.hobbyName}`,
                capabilities: ['text', 'audio', 'svg_generation']
            })
        }

        if (Array.isArray(aiRes.initialSkills) && aiRes.initialSkills.length > 0) {
            for (const skillData of aiRes.initialSkills) {
                const skillSlug = skillData.slug || skillData.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
                const existingSkill = await HobbySkill.findOne({ hobbyId: hobby._id, slug: skillSlug })
                if (!existingSkill) {
                    await HobbySkill.create({
                        hobbyId: hobby._id,
                        name: skillData.name,
                        slug: skillSlug,
                        category: skillData.category || hobby.category,
                        skillType: ['knowledge', 'physical', 'creative', 'technical', 'strategic'].includes(skillData.skillType) ? skillData.skillType : 'technical',
                        description: skillData.description || '',
                        assessmentMethods: ['text'],
                        isActive: true
                    })
                }
            }
        }

        const userHobby = await UserHobby.create({
            userId,
            hobbyId: hobby._id,
            currentStage: 'active_learning',
            status: 'active'
        })

        return userHobby

    } catch (err) {
        console.error('[SkillLearning] Error detecting hobby via AI:', err.message)
        return null
    }
}

// ─── Step 1: Resolve UserHobby & Conversation Context ─────────────────────────

async function resolveUserHobbyAndConversation({ userId, conversationId, reqUserHobbyId, message, modelChoice }) {
    let conversation = null
    if (conversationId) {
        conversation = await Conversation.findById(conversationId)
    }

    let userHobby = null
    if (conversation && conversation.userHobbyId) {
        userHobby = await UserHobby.findById(conversation.userHobbyId)
    }
    if (!userHobby && reqUserHobbyId) {
        userHobby = await UserHobby.findById(reqUserHobbyId)
    }
    if (!userHobby) {
        userHobby = await UserHobby.findOne({ userId, status: 'active' })
    }

    if (!userHobby) {
        userHobby = await detectAndCreateHobbyWithAi(message, userId, modelChoice)
    }

    if (!userHobby) {
        const tempTitle = message.trim().slice(0, 35) + '...'
        const clarificationText = 'Welcome! Which hobby or skill would you like to learn today? (For example: Piano, Guitar, Sourdough Baking, Chess, Drawing, Songwriting, Cooking)'

        let pendingConversation = conversation
        if (!pendingConversation) {
            const placeholderHobby = await Hobby.findOneAndUpdate(
                { slug: 'general-learning' },
                { name: 'General Learning', slug: 'general-learning', capabilities: ['text', 'audio', 'svg_generation'] },
                { upsert: true, new: true }
            )
            userHobby = await UserHobby.create({
                userId,
                hobbyId: placeholderHobby._id,
                currentStage: 'onboarding',
                status: 'active'
            })
            pendingConversation = await Conversation.create({
                userId,
                userHobbyId: userHobby._id,
                title: tempTitle,
                messageCount: 0
            })
        }

        const assistantMsgDoc = await Message.create({
            conversationId: pendingConversation._id,
            role: 'assistant',
            content: clarificationText,
            contentType: 'text'
        })

        return {
            needsOnboardingClarification: true,
            clarificationResponse: {
                success: true,
                conversationId: pendingConversation._id,
                messageId: assistantMsgDoc._id,
                responseType: RESPONSE_TYPE.CLARIFICATION,
                skillInfo: {
                    skillName: 'Onboarding',
                    currentLevel: SKILL_LEVEL.BEGINNER,
                    score: 0
                },
                learningContent: {
                    formsDelivered: ['text'],
                    text: clarificationText
                }
            }
        }
    }

    if (!conversation) {
        conversation = await Conversation.create({
            userId,
            userHobbyId: userHobby._id,
            title: message.trim().slice(0, 35) + '...',
            messageCount: 0
        })
    }

    return { conversation, userHobby, needsOnboardingClarification: false }
}

// ─── Step 2: Resolve Skill Metadata & User Progress ───────────────────────────

const SKILL_MATCH_STOP_WORDS = new Set([
    'about', 'again', 'also', 'and', 'are', 'can', 'could', 'does', 'explain', 'for',
    'from', 'have', 'help', 'how', 'into', 'learn', 'lesson', 'like', 'more', 'need',
    'please', 'show', 'skill', 'teach', 'that', 'the', 'this', 'want', 'what', 'with', 'you', 'your'
])

function getMeaningfulWords(value = '') {
    return new Set(
        String(value)
            .toLowerCase()
            .match(/[a-z0-9]+/g)
            ?.filter(word => word.length >= 3 && !SKILL_MATCH_STOP_WORDS.has(word)) || []
    )
}

function findSkillMatchingMessage(skills = [], message = '') {
    const messageWords = getMeaningfulWords(message)
    if (messageWords.size === 0) return null

    let bestSkill = null
    let bestScore = 0

    for (const skill of skills) {
        const nameWords = getMeaningfulWords(skill.name)
        const detailWords = getMeaningfulWords(`${skill.category || ''} ${skill.description || ''}`)
        let score = 0

        for (const word of messageWords) {
            if (nameWords.has(word)) score += 3
            else if (detailWords.has(word)) score += 1
        }

        if (score > bestScore) {
            bestScore = score
            bestSkill = skill
        }
    }

    return bestSkill
}

async function resolveSkillMetadataAndProgress({ userHobbyId, reqHobbySkillId, message = '' }) {
    let hobbySkillId = reqHobbySkillId || null
    let hobbySkill = null
    const userHobby = await UserHobby.findById(userHobbyId).populate('hobbyId')

    if (hobbySkillId) {
        hobbySkill = await HobbySkill.findById(hobbySkillId)
    }

    if (!hobbySkill && userHobby) {
        const targetHobbyId = userHobby.hobbyId?._id || userHobby.hobbyId
        const activeSkills = await HobbySkill.find({ hobbyId: targetHobbyId, isActive: true })
            .sort({ createdAt: 1 })
        hobbySkill = findSkillMatchingMessage(activeSkills, message) || activeSkills[0] || null

        if (!hobbySkill && targetHobbyId) {
            const hobbyName = userHobby.hobbyId?.name || 'Skill'
            const slug = (userHobby.hobbyId?.slug || 'hobby') + '-fundamentals'
            hobbySkill = await HobbySkill.findOne({ slug })
            if (!hobbySkill) {
                hobbySkill = await HobbySkill.create({
                    hobbyId: targetHobbyId,
                    name: `${hobbyName} Fundamentals`,
                    slug,
                    category: userHobby.hobbyId?.category || 'General',
                    skillType: 'knowledge',
                    description: `Core concepts and fundamentals for ${hobbyName}`,
                    isActive: true
                })
            }
        }
    }

    if (hobbySkill) {
        hobbySkillId = hobbySkill._id
    }

    let userSkill = null
    if (hobbySkillId) {
        userSkill = await UserSkill.findOne({ userHobbyId, hobbySkillId })
    }

    const currentLevel = userSkill?.level || SKILL_LEVEL.BEGINNER
    const currentScore = userSkill?.score ?? 0
    const strengths = userSkill?.strengths || []
    const weaknesses = userSkill?.weaknesses || []

    return {
        hobbySkill,
        userSkill,
        currentLevel,
        currentScore,
        strengths,
        weaknesses
    }
}

// ─── Helper: Update User Progress & Calculate Level ───────────────────────────

async function updateUserSkillProgress({ userId, userHobbyId, hobbySkill, userSkill, evalData = {} }) {
    if (!hobbySkill) return { currentLevel: SKILL_LEVEL.BEGINNER, currentScore: 0 }

    if (!userSkill) {
        userSkill = await UserSkill.findOne({ userHobbyId, hobbySkillId: hobbySkill._id })
    }

    const currentScore = userSkill?.score ?? 0
    // Default scoreDelta is 0 for regular chat messages (XP is earned strictly from quizzes & task completions!)
    const scoreDelta = typeof evalData.scoreDelta === 'number' ? evalData.scoreDelta : 0
    let newScore = Math.max(0, Math.min(100, currentScore + scoreDelta))

    let newLevel = SKILL_LEVEL.BEGINNER
    if (newScore >= 76) newLevel = SKILL_LEVEL.EXPERT
    else if (newScore >= 51) newLevel = SKILL_LEVEL.ADVANCED
    else if (newScore >= 26) newLevel = SKILL_LEVEL.INTERMEDIATE

    const newStrengths = Array.isArray(evalData.newStrengths) ? evalData.newStrengths : []
    const newWeaknesses = Array.isArray(evalData.newWeaknesses) ? evalData.newWeaknesses : []

    const updatedStrengths = Array.from(new Set([...(userSkill?.strengths || []), ...newStrengths]))
    const updatedWeaknesses = Array.from(new Set([...(userSkill?.weaknesses || []), ...newWeaknesses]))

    if (!userSkill) {
        userSkill = await UserSkill.create({
            userId,
            userHobbyId,
            hobbySkillId: hobbySkill._id,
            score: newScore,
            level: newLevel,
            strengths: updatedStrengths,
            weaknesses: updatedWeaknesses,
            lastPracticedAt: new Date()
        })
    } else {
        userSkill.score = newScore
        userSkill.level = newLevel
        userSkill.strengths = updatedStrengths
        userSkill.weaknesses = updatedWeaknesses
        userSkill.lastPracticedAt = new Date()
        await userSkill.save()
    }

    return {
        currentLevel: newLevel,
        currentScore: newScore,
        userSkill
    }
}

// ─── Helper: Record & Coalesce Practice Sessions ──────────────────────────────

async function recordLearningPracticeSession({
    userId,
    userHobbyId,
    lessonText = '',
    formsDelivered = [],
    quizCount = 0,
    topicTitle = 'AI Learning Session',
    explicitSeconds = null
}) {
    if (!userHobbyId) return null

    let durationSeconds = 0
    if (typeof explicitSeconds === 'number' && explicitSeconds > 0) {
        durationSeconds = Math.round(explicitSeconds)
    } else {
        const wordCount = (lessonText || '').split(/\s+/).filter(Boolean).length
        durationSeconds = Math.max(60, Math.round(wordCount * 0.3 + 30))

        if (formsDelivered.includes('svg')) durationSeconds += 60
        if (formsDelivered.includes('checklist')) durationSeconds += 60
        if (formsDelivered.includes('musical_notes')) durationSeconds += 90
        if (formsDelivered.includes('code_snippet')) durationSeconds += 90
        if (quizCount > 0) durationSeconds += (quizCount * 60)
    }

    try {
        const fifteenMinsAgo = new Date(Date.now() - 15 * 60 * 1000)
        let session = await PracticeSession.findOne({
            userHobbyId,
            status: 'completed',
            createdAt: { $gte: fifteenMinsAgo }
        }).sort({ createdAt: -1 })

        if (session) {
            session.durationSeconds = (session.durationSeconds || 0) + durationSeconds
            await session.save()
            return session
        }

        return await PracticeSession.create({
            userId,
            userHobbyId,
            title: topicTitle,
            durationSeconds,
            status: 'completed',
            score: 100
        })
    } catch (err) {
        console.error('[SkillLearning] Error recording PracticeSession:', err.message)
        return null
    }
}


// ─── Step 3: Fetch Historical Practice & Chat Context ─────────────────────────

async function fetchLearningHistoryContext({ userHobbyId, conversationId }) {
    const recentPractice = await PracticeSession.find({ userHobbyId })
        .sort({ createdAt: -1 })
        .limit(5)
        .lean()

    const recentMessages = await Message.find({ conversationId })
        .sort({ createdAt: 1 })
        .limit(10)
        .lean()

    return { recentPractice, recentMessages }
}

// ─── Step 4: Build AI Context & Output Contract ────────────────────────────────

const DELIVERABLE_AI_FORMS = new Set([
    LEARNING_FORM.TEXT,
    LEARNING_FORM.SVG,
    LEARNING_FORM.INTERACTIVE_QUIZ,
    LEARNING_FORM.FLASHCARD,
    LEARNING_FORM.MUSICAL_NOTES,
    LEARNING_FORM.CHECKLIST,
    LEARNING_FORM.CODE_SNIPPET
])

function normalizeRequestedForms(forms) {
    if (!Array.isArray(forms)) return []
    return Array.from(new Set(forms.filter(form => DELIVERABLE_AI_FORMS.has(form))))
}

function compactConversationForAi(recentMessages = []) {
    return recentMessages.slice(-6).map(message => {
        let textContent = message.content
        if (message.role === 'assistant') {
            try {
                const parsed = JSON.parse(message.content)
                textContent = parsed.text || parsed.learningContent?.text || message.content
            } catch (_) {
                textContent = message.content
            }
        }

        const normalizedContent = String(textContent || '').trim()
        const maxChars = 900
        return {
            role: message.role,
            content: normalizedContent.length > maxChars
                ? `${normalizedContent.slice(0, maxChars - 24)}… [truncated]`
                : normalizedContent
        }
    })
}

function constructPlanningContext({
    userHobby,
    hobbySkill,
    currentLevel,
    currentScore,
    strengths = [],
    weaknesses = [],
    recentPractice = [],
    requestedForms = []
}) {
    const history = recentPractice
        .slice(-5)
        .map(p => `${p.title || p.task || 'Practice'} (${p.score ?? 'unscored'}, ${p.status || 'unknown'})`)
        .join('; ')

    const hobbyName = userHobby?.hobbyId?.name || hobbySkill?.name || 'Skill'
    const hobbyGoal = userHobby?.goal || 'Master fundamentals'

    return `ACTIVE HOBBY TO TEACH: ${hobbyName}
LEARNING GOAL: ${hobbyGoal}
SKILL MODULE: ${hobbySkill?.name || hobbyName}
TYPE: ${hobbySkill?.skillType || 'knowledge'}
LEVEL: ${currentLevel || SKILL_LEVEL.BEGINNER} (${currentScore ?? 0}/100)
STRENGTHS: ${strengths.join(', ') || 'none'}
WEAKNESSES: ${weaknesses.join(', ') || 'none'}
RECENT PRACTICE: ${history || 'none'}
REQUESTED FORMS: ${requestedForms.join(', ') || 'none'}`
}

function constructSystemInstruction({ planningContext }) {
    const hobbyMatch = planningContext.match(/ACTIVE HOBBY TO TEACH: (.*)/)
    const hobbyName = hobbyMatch ? hobbyMatch[1].trim() : 'the requested hobby'

    return `You are a dedicated, world-class AI coach specifically expert in teaching ${hobbyName}.

${planningContext}

CRITICAL LESSON SCOPING RULES:
- ALL YOUR LESSONS, CONCEPTS, EXPLANATIONS, EXAMPLES, AND DRILLS MUST BE STRICTLY ABOUT ${hobbyName.toUpperCase()}.
- DO NOT TEACH OR MENTION UNRELATED SUBJECTS (e.g. Do NOT teach computer programming or coding unless ${hobbyName} is explicitly Coding or Software Development!).
- When a pass-1 lesson plan is supplied, use it as the resolved intent and scope. Answer the learner directly; do not mention the plan or this prompt.

LESSON QUALITY
- The text must be self-contained, accurate, and structured in short Markdown sections. Start with the direct answer or key action, then explain only the plan's required points in a useful order.
- Beginner: define essential terms and give numbered, concrete steps. Intermediate: focus on execution and common mistakes. Advanced/expert: focus on precision, variations, diagnostics, and nuanced trade-offs; do not repeat basic definitions.
- The latest learner message is the current topic. Conversation history is only context: do not repeat an earlier concept, example, drill, or foundational landmark (such as C or Middle C) unless the latest message explicitly asks for it or it is essential to answering the current topic. When the learner changes topic, acknowledge the switch by answering the new topic directly.
- Always include text. Include exactly the plan's selected forms: text plus at most one additional form. Do not invent URLs, asset IDs, external sources, or user progress.
- A requested form is a preference, not a reason to add irrelevant content. Do not output audio or video; this endpoint has no audio/video delivery path.
- Include a measurable practiceTask only when the plan calls for one. Include eval only when the learner supplied an actual practice or quiz result.
- Delivery integrity is mandatory: never say “quiz”, “test”, “knowledge check”, “choose the correct answer”, or tell the learner to answer questions unless formsToDeliver includes interactive_quiz and the quiz array is present and non-empty. When interactive_quiz is selected, include 1-3 complete quiz objects and set formsToDeliver to ["text", "interactive_quiz"]. If it is not selected, finish with a practiceTask or a plain next step instead.

FORM CONTRACTS
- svg: a complete, self-contained SVG string. Use a tight viewBox, 15px+ padding, dark-theme-safe contrast, readable labels (font-size 12+), no clipped or overlapping content, and no external assets or JavaScript.
- interactive_quiz: its form name in formsToDeliver is "interactive_quiz", but its JSON payload key MUST be "quiz": [{ id, question, options: [4 choices], correctIndex, explanation }]. Never use "interactive_quiz" as a JSON payload key.
- flashcard: 3-6 objects { front, back }.
- musical_notes: { instrument, bpm, notes: [{ pitch, startBeat, durationBeats, velocity, finger }] }. pitch is scientific pitch notation (for example C4); startBeat is zero-based; durationBeats is positive; velocity is 0-127; finger is 1-5 or null.
- checklist: 3-7 objects { step, title, instruction }.
- code_snippet: { language, code, expectedOutput }.

OUTPUT CONTRACT
For clarification, return exactly:
{ "responseType": "clarification", "learningContent": { "text": "one concise question" } }

For a lesson, return exactly this top-level shape, adding only the field for the selected optional form:
{
  "responseType": "learning_content",
  "learningContent": {
    "formsToDeliver": ["text"],
    "text": "structured Markdown lesson",
    "practiceTask": "optional measurable task",
    "eval": { "scoreDelta": 0, "newStrengths": [], "newWeaknesses": [] }
  }
}
When interactive_quiz is selected, the lesson shape is:
{
  "responseType": "learning_content",
  "learningContent": {
    "formsToDeliver": ["text", "interactive_quiz"],
    "text": "structured Markdown lesson",
    "quiz": [{ "id": "q_1", "question": "...", "options": ["...", "...", "...", "..."], "correctIndex": 0, "explanation": "..." }]
  }
}
Omit practiceTask and eval when they do not apply. Return JSON only.`
}

// ─── Main Unified API Endpoint: Learn Skill Chatbot ────────────────────────────

/**
 * Single Unified API Endpoint: Learn Skill Chatbot
 * POST /api/v1/ai/learn-skill
 */
exports.learnSkill = async (req, res) => {
    const startTime = Date.now()

    try {
        const { message, conversationId, userHobbyId: reqUserHobbyId, hobbySkillId: reqHobbySkillId, options = {} } = req.body
        const userId = req.userId || req.user?._id || req.user?.uid || req.query?.userId || req.body?.userId

        if (!message || typeof message !== 'string' || message.trim() === '') {
            return sendResponse(res, 400, { info: 'message is required.' })
        }

        const modelChoice = options.model || 'gemini'
        const targetModel = modelChoice === 'gemini-lite' ? 'gemini' : modelChoice
        const modelVariant = options.modelVariant || (targetModel === 'gemini' ? 'gemini-3.1-flash-lite' : null)
        const requestedForms = normalizeRequestedForms(options.requestedForms)

        // STEP 1: Resolve Conversation & UserHobby (with AI Auto-Enrollment)
        const hobbyCtx = await resolveUserHobbyAndConversation({ userId, conversationId, reqUserHobbyId, message, modelChoice: targetModel })
        if (hobbyCtx.needsOnboardingClarification) {
            return sendResponse(res, 200, hobbyCtx.clarificationResponse)
        }

        const { conversation, userHobby } = hobbyCtx
        const userHobbyId = userHobby._id

        // STEP 2 & 3: Resolve Skill Metadata, User Progress & History Context in Parallel
        const [skillCtx, historyCtx] = await Promise.all([
            resolveSkillMetadataAndProgress({ userHobbyId, reqHobbySkillId, message }),
            fetchLearningHistoryContext({ userHobbyId, conversationId: conversation._id })
        ])

        const { recentPractice, recentMessages } = historyCtx


        // STEP 4: Resolve a compact lesson plan, then generate the final structured response.
        const learningContext = {
            userHobby,
            hobbySkill: skillCtx.hobbySkill,
            currentLevel: skillCtx.currentLevel,
            currentScore: skillCtx.currentScore,
            strengths: skillCtx.strengths,
            weaknesses: skillCtx.weaknesses,
            recentPractice,
            requestedForms
        }
        const planningContext = constructPlanningContext(learningContext)
        const systemInstruction = constructSystemInstruction({ planningContext })

        // Keep enough conversational continuity without resending previous long lessons.
        const chatMessagesForAi = compactConversationForAi(recentMessages)
        chatMessagesForAi.push({ role: 'user', content: message.trim() })

        // LOG INPUT PARAMETERS SENT TO AI
        console.log('\n============================== [AI REQUEST PARAMETERS] ==============================')
        console.log(`[Target Model]    : ${targetModel} (${modelVariant || 'default'})`)
        console.log(`[User Context]    : User ID: ${userId} | UserHobby ID: ${userHobbyId}`)
        console.log(`[Skill Context]   : ${skillCtx.hobbySkill?.name || 'General Skill'} | Level: ${skillCtx.currentLevel} | Score: ${skillCtx.currentScore}`)
        console.log(`[Requested Forms] : ${requestedForms.length > 0 ? requestedForms.join(', ') : 'None specified'}`)
        console.log('\n--- SYSTEM INSTRUCTION SENT TO AI ---')
        console.log(systemInstruction)
        console.log('\n--- CHAT MESSAGES HISTORY SENT TO AI ---')
        console.log(JSON.stringify(chatMessagesForAi, null, 2))
        console.log('=====================================================================================\n')

        const aiResponse = await generateStructuredContent({
            model: targetModel,
            systemInstruction,
            messages: chatMessagesForAi,
            planningContext,
            temperature: 0.5,
            modelVariant,
            twoPass: true,
            plannerMaxOutputTokens: 700,
            maxOutputTokens: 2600
        })

        // LOG RESPONSE RECEIVED FROM AI
        console.log('\n============================== [AI RESPONSE RECEIVED] ==============================')
        console.log(JSON.stringify(aiResponse, null, 2))
        console.log('====================================================================================\n')

        const responseType = aiResponse.responseType || RESPONSE_TYPE.LEARNING_CONTENT
        const learningContent = aiResponse.learningContent || {}

        // The form identifier is "interactive_quiz", but the public payload field is "quiz".
        // Accept the model's occasional form-name alias so a valid quiz is never silently dropped.
        if (!Array.isArray(learningContent.quiz) && Array.isArray(learningContent.interactive_quiz)) {
            learningContent.quiz = learningContent.interactive_quiz
        }


        // STEP 5A: Handle Clarification Response Branch
        if (responseType === RESPONSE_TYPE.CLARIFICATION) {
            const clarificationText = learningContent.text || aiResponse.text || 'Could you please clarify your request?'

            const [_, assistantMsgDoc] = await Promise.all([
                Message.create({
                    conversationId: conversation._id,
                    role: 'user',
                    content: message.trim(),
                    contentType: LEARNING_FORM.TEXT
                }),
                Message.create({
                    conversationId: conversation._id,
                    role: 'assistant',
                    content: clarificationText,
                    contentType: LEARNING_FORM.TEXT
                }),
                Conversation.findByIdAndUpdate(conversation._id, {
                    $inc: { messageCount: 2 },
                    $set: {
                        lastMessagePreview: clarificationText.slice(0, 80),
                        lastMessageAt: new Date()
                    }
                })
            ])

            return sendResponse(res, 200, {
                success: true,
                conversationId: conversation._id,
                messageId: assistantMsgDoc._id,
                responseType: RESPONSE_TYPE.CLARIFICATION,
                skillInfo: {
                    skillName: skillCtx.hobbySkill?.name || 'Skill',
                    currentLevel: skillCtx.currentLevel,
                    score: skillCtx.currentScore
                },
                learningContent: {
                    formsDelivered: [LEARNING_FORM.TEXT],
                    text: clarificationText
                }
            })
        }

        // STEP 5B: Handle Learning Content Response Branch
        // 1. Inspect what data keys actually exist in the AI payload:
        const actualPresentForms = [LEARNING_FORM.TEXT]
        if (learningContent.svg && typeof learningContent.svg === 'string' && learningContent.svg.trim().length > 0) {
            actualPresentForms.push(LEARNING_FORM.SVG)
        }
        if (Array.isArray(learningContent.quiz) && learningContent.quiz.length > 0) {
            actualPresentForms.push(LEARNING_FORM.INTERACTIVE_QUIZ)
        }
        if (Array.isArray(learningContent.flashcards) && learningContent.flashcards.length > 0) {
            actualPresentForms.push(LEARNING_FORM.FLASHCARD)
        }
        if (learningContent.musicalNotes && typeof learningContent.musicalNotes === 'object') {
            actualPresentForms.push(LEARNING_FORM.MUSICAL_NOTES)
        }
        if (Array.isArray(learningContent.checklist) && learningContent.checklist.length > 0) {
            actualPresentForms.push(LEARNING_FORM.CHECKLIST)
        }
        if (learningContent.video && typeof learningContent.video === 'object') {
            actualPresentForms.push(LEARNING_FORM.VIDEO)
        }
        if (learningContent.codeSnippet && typeof learningContent.codeSnippet === 'object') {
            actualPresentForms.push(LEARNING_FORM.CODE_SNIPPET)
        }

        // 2. Validate & Repair: Only retain forms that have valid present data
        let formsToDeliver = Array.isArray(learningContent.formsToDeliver) && learningContent.formsToDeliver.length > 0
            ? learningContent.formsToDeliver.filter(f => DELIVERABLE_AI_FORMS.has(f) && actualPresentForms.includes(f))
            : (requestedForms.length > 0 ? requestedForms.filter(f => actualPresentForms.includes(f)) : [LEARNING_FORM.TEXT])

        if (!formsToDeliver.includes(LEARNING_FORM.TEXT)) {
            formsToDeliver.unshift(LEARNING_FORM.TEXT)
        }

        formsToDeliver = Array.from(new Set(formsToDeliver))

        if (formsToDeliver.length > 2) {
            formsToDeliver = formsToDeliver.slice(0, 2)
        }


        const formsDelivered = []
        const assetIds = []
        const responseLearningContent = {}
        const taskPromises = []

        // Process Text Form
        if (formsToDeliver.includes(LEARNING_FORM.TEXT) || learningContent.text) {
            responseLearningContent.text = processTextForm(learningContent)
            formsDelivered.push(LEARNING_FORM.TEXT)
        }

        // Process SVG Form
        if (formsToDeliver.includes(LEARNING_FORM.SVG) && learningContent.svg) {
            taskPromises.push(
                processSvgForm(learningContent, skillCtx.hobbySkill, userId, userHobbyId, assetIds).then(svgRes => {
                    if (svgRes) {
                        responseLearningContent.svg = svgRes
                        formsDelivered.push(LEARNING_FORM.SVG)
                    }
                })
            )
        }

        // Process Interactive Quiz Form
        if (learningContent.quiz && Array.isArray(learningContent.quiz) && learningContent.quiz.length > 0) {
            const quizRes = processQuizForm(learningContent)
            if (quizRes) {
                responseLearningContent.quiz = quizRes
                formsDelivered.push(LEARNING_FORM.INTERACTIVE_QUIZ)
            }
        }

        // Process Flashcards Form
        const fcRaw = learningContent.flashcards || learningContent.flashcard
        if (fcRaw && Array.isArray(fcRaw) && fcRaw.length > 0) {
            const fcRes = processFlashcardsForm(learningContent)
            if (fcRes) {
                responseLearningContent.flashcards = fcRes
                responseLearningContent.flashcard = fcRes
                formsDelivered.push(LEARNING_FORM.FLASHCARD)
            }
        }

        // Process Musical Notes Form
        if (learningContent.musicalNotes && learningContent.musicalNotes.notes) {
            const mnRes = processMusicalNotesForm(learningContent)
            if (mnRes) {
                responseLearningContent.musicalNotes = mnRes
                formsDelivered.push(LEARNING_FORM.MUSICAL_NOTES)
            }
        }

        // Process Checklist Form
        if (learningContent.checklist && Array.isArray(learningContent.checklist) && learningContent.checklist.length > 0) {
            const clRes = processChecklistForm(learningContent)
            if (clRes) {
                responseLearningContent.checklist = clRes
                formsDelivered.push(LEARNING_FORM.CHECKLIST)
            }
        }

        // Process Video Form
        if (learningContent.video && learningContent.video.embedUrl) {
            const vRes = processVideoForm(learningContent)
            if (vRes) {
                responseLearningContent.video = vRes
                formsDelivered.push(LEARNING_FORM.VIDEO)
            }
        }

        // Process Code Snippet Form
        if (learningContent.codeSnippet && learningContent.codeSnippet.code) {
            const csRes = processCodeSnippetForm(learningContent)
            if (csRes) {
                responseLearningContent.codeSnippet = csRes
                formsDelivered.push(LEARNING_FORM.CODE_SNIPPET)
            }
        }

        if (learningContent.practiceTask) {
            responseLearningContent.practiceTask = learningContent.practiceTask
        }

        // Execute user message creation and asset tasks in parallel
        await Promise.all([
            Message.create({
                conversationId: conversation._id,
                role: 'user',
                content: message.trim(),
                contentType: LEARNING_FORM.TEXT
            }),
            ...taskPromises
        ])

        const deliveredLearningContent = {
            formsDelivered: Array.from(new Set(formsDelivered)),
            ...responseLearningContent
        }
        const assistantContentPayload = JSON.stringify(deliveredLearningContent)
        const previewSnippet = responseLearningContent.text
            ? responseLearningContent.text.slice(0, 80)
            : 'Generated lesson'

        // Execute assistant message creation, conversation update, and UserSkill progress update in parallel
        const [assistantMsgDoc, _, updatedProgress] = await Promise.all([
            Message.create({
                conversationId: conversation._id,
                role: 'assistant',
                content: assistantContentPayload,
                contentType: LEARNING_FORM.TEXT,
                assetIds
            }),
            Conversation.findByIdAndUpdate(conversation._id, {
                $inc: { messageCount: 2 },
                $set: {
                    lastMessagePreview: previewSnippet,
                    lastMessageAt: new Date()
                }
            }),
            updateUserSkillProgress({
                userId,
                userHobbyId,
                hobbySkill: skillCtx.hobbySkill,
                userSkill: skillCtx.userSkill,
                evalData: learningContent.eval || {}
            }),
            recordLearningPracticeSession({
                userId,
                userHobbyId,
                lessonText: responseLearningContent.text || '',
                formsDelivered: deliveredLearningContent.formsDelivered || [],
                quizCount: Array.isArray(responseLearningContent.quiz) ? responseLearningContent.quiz.length : 0,
                topicTitle: skillCtx.hobbySkill?.name || 'AI Learning Session'
            })
        ])

        const latencyMs = Date.now() - startTime
        console.log(`[SkillLearning] Lesson generated in ${latencyMs}ms for user ${userId}. Forms delivered (${formsDelivered.length}): [${formsDelivered.join(', ')}]`)

        return sendResponse(res, 200, {
            success: true,
            conversationId: conversation._id,
            messageId: assistantMsgDoc._id,
            responseType: RESPONSE_TYPE.LEARNING_CONTENT,
            skillInfo: {
                skillName: skillCtx.hobbySkill?.name || 'Skill',
                currentLevel: updatedProgress.currentLevel,
                score: updatedProgress.currentScore
            },
            learningContent: deliveredLearningContent
        })

    } catch (err) {
        console.error('[SkillLearning] Error in learnSkill:', err)
        return sendResponse(res, 500, { info: `Skill learning failed: ${err.message}` }, err)
    }
}


// ─── Paginated Chat History Endpoint ──────────────────────────────────────────

/**
 * GET /api/v1/ai/chat-history
 * GET /api/v1/ai/conversations/:conversationId/messages
 * Query params: page=1&limit=20&userId=...
 */
exports.getConversationMessages = async (req, res) => {
    try {
        let conversationId = req.params.conversationId || req.query.conversationId
        const userHobbyId = req.query.userHobbyId
        const userId = req.userId || req.user?._id || req.user?.uid || req.query?.userId || req.body?.userId
        const page = Math.max(1, parseInt(req.query.page) || 1)
        const limit = Math.min(50, Math.max(1, parseInt(req.query.limit) || 20))

        let conversation = null
        if (conversationId && conversationId !== 'current') {
            // A supplied conversation must belong to the current user.
            conversation = await Conversation.findOne({ _id: conversationId, userId })
        } else if (userHobbyId) {
            // Find the user's most recently active conversation for this specific userHobbyId
            conversation = await Conversation.findOne({ userId, userHobbyId }).sort({ lastMessageAt: -1, updatedAt: -1 })
        } else {
            // Find the user's most recently active conversation across any hobby
            conversation = await Conversation.findOne({ userId }).sort({ lastMessageAt: -1, updatedAt: -1 })
        }

        if (!conversation) {
            return sendResponse(res, 200, {
                success: true,
                conversationId: null,
                page: 1,
                limit,
                totalMessages: 0,
                totalPages: 0,
                hasMore: false,
                messages: []
            })
        }

        conversationId = conversation._id

        const totalMessages = await Message.countDocuments({ conversationId })
        const totalPages = Math.ceil(totalMessages / limit)
        const skip = (page - 1) * limit

        // Page 1 is the latest chat page. Reverse it before returning so the UI
        // still receives messages in natural oldest-to-newest display order.
        const rawMessages = await Message.find({ conversationId })
            .sort({ createdAt: -1, _id: -1 })
            .skip(skip)
            .limit(limit)
            .lean()

        rawMessages.reverse()

        let skillInfo = null
        const effectiveUserHobbyId = conversation.userHobbyId || userHobbyId
        if (effectiveUserHobbyId) {
            const userHobby = await UserHobby.findById(effectiveUserHobbyId).populate('hobbyId', 'name').lean()
            if (userHobby) {
                const userSkill = await UserSkill.findOne({ userHobbyId: effectiveUserHobbyId }).lean()
                skillInfo = {
                    skillName: userHobby.hobbyId?.name || 'Skill',
                    currentLevel: userSkill?.level || 'beginner',
                    score: userSkill?.score || 0
                }
            }
        }

        const formattedMessages = rawMessages.map(msg => {
            let parsedContent = null
            if (msg.role === 'assistant' && msg.content) {
                try {
                    parsedContent = JSON.parse(msg.content)
                    if (parsedContent?.learningContent) {
                        const lc = parsedContent.learningContent
                        if (lc.flashcard && !lc.flashcards) lc.flashcards = lc.flashcard
                        else if (lc.flashcards && !lc.flashcard) lc.flashcard = lc.flashcards
                    }
                } catch (e) {
                    parsedContent = { text: msg.content }
                }
            }

            return {
                id: msg._id,
                conversationId: msg.conversationId,
                role: msg.role,
                content: msg.content,
                parsedContent,
                contentType: msg.contentType,
                assetIds: msg.assetIds || [],
                createdAt: msg.createdAt
            }
        })

        return sendResponse(res, 200, {
            success: true,
            conversationId,
            skillInfo,
            page,
            limit,
            totalMessages,
            totalPages,
            hasMore: page < totalPages,
            messages: formattedMessages
        })

    } catch (err) {
        console.error('[SkillLearning] Error in getConversationMessages:', err)
        return sendResponse(res, 500, { info: `Failed to fetch conversation history: ${err.message}` }, err)
    }
}

/**
 * POST /api/v1/ai/submit-quiz
 * Evaluates a learner's quiz answer, deduplicates attempts, enforces 20 XP daily cap, and awards +2 XP.
 */
exports.submitQuizAnswer = async (req, res) => {
    try {
        const userId = req.userId || req.user?._id || req.user?.uid || req.query?.userId || req.body?.userId
        const { userHobbyId, hobbySkillId, quizId, questionIndex, selectedIndex, correctIndex } = req.body

        if (!userHobbyId || !quizId || questionIndex === undefined || selectedIndex === undefined || correctIndex === undefined) {
            return sendResponse(res, 400, { success: false, message: 'Missing required quiz submission fields.' })
        }

        const isCorrect = Number(selectedIndex) === Number(correctIndex)
        const QuizAttempt = require('../Models/QuizAttempt')
        const UserSkill = require('../Models/UserSkill')

        // 1. Prevent duplicate XP for the same question
        const existingAttempt = await QuizAttempt.findOne({ userId, quizId, questionIndex })
        if (existingAttempt) {
            return sendResponse(res, 200, {
                success: true,
                message: 'Question already evaluated.',
                isCorrect: existingAttempt.isCorrect,
                xpAwarded: 0,
                alreadyAnswered: true
            })
        }

        let userSkill = null
        if (hobbySkillId) {
            userSkill = await UserSkill.findOne({ userHobbyId, hobbySkillId })
        } else {
            userSkill = await UserSkill.findOne({ userHobbyId }).sort({ updatedAt: -1 })
        }

        // 2. Daily Cap Pacing Logic (20 XP max per calendar day)
        const todayStr = new Date().toISOString().split('T')[0]
        const lastDateStr = userSkill?.lastXpDate ? new Date(userSkill.lastXpDate).toISOString().split('T')[0] : ''

        let dailyXp = userSkill?.dailyXpEarned || 0
        if (lastDateStr !== todayStr) {
            dailyXp = 0 // Reset daily counter for a new calendar day
        }

        const DAILY_CAP = 20
        let xpToAward = 0

        if (isCorrect) {
            const baseXP = 2 // +2 XP per correct quiz answer
            const remainingCap = Math.max(0, DAILY_CAP - dailyXp)
            xpToAward = Math.min(baseXP, remainingCap)
        }

        // 3. Save Quiz Attempt Record
        await QuizAttempt.create({
            userId,
            userHobbyId,
            hobbySkillId: userSkill?.hobbySkillId || userHobbyId,
            quizId,
            questionIndex,
            selectedIndex,
            correctIndex,
            isCorrect,
            xpAwarded: xpToAward
        })

        // 4. Update UserSkill Score & Level
        let newScore = userSkill?.score || 0
        let newLevel = userSkill?.level || SKILL_LEVEL.BEGINNER

        if (userSkill && xpToAward > 0) {
            newScore = Math.min(100, (userSkill.score || 0) + xpToAward)
            userSkill.score = newScore
            userSkill.dailyXpEarned = dailyXp + xpToAward
            userSkill.lastXpDate = new Date()

            if (newScore >= 76) newLevel = SKILL_LEVEL.EXPERT
            else if (newScore >= 51) newLevel = SKILL_LEVEL.ADVANCED
            else if (newScore >= 26) newLevel = SKILL_LEVEL.INTERMEDIATE
            else newLevel = SKILL_LEVEL.BEGINNER

            userSkill.level = newLevel
            await userSkill.save()

            // Invalidate leaderboard cache so next fetch gets updated scores
            try {
                const { invalidateLeaderboardCache } = require('./leaderboardController')
                invalidateLeaderboardCache()
            } catch (e) {
                // Ignore cache invalidation error
            }
        }

        // Record Practice Session (+1 min credit for quiz attempt)
        await recordLearningPracticeSession({
            userId,
            userHobbyId,
            quizCount: 1,
            topicTitle: 'Quiz Practice Drill',
            explicitSeconds: 60
        }).catch(() => {})

        return sendResponse(res, 200, {
            success: true,
            isCorrect,
            xpAwarded: xpToAward,
            newScore,
            newLevel,
            dailyXpEarned: dailyXp + xpToAward,
            isCapReached: (dailyXp + xpToAward) >= DAILY_CAP
        })
    } catch (err) {
        console.error('[SkillLearning] Error in submitQuizAnswer:', err)
        return sendResponse(res, 500, { success: false, message: 'Failed to submit quiz answer.', error: err.message })
    }
}

/**
 * POST /api/v1/ai/complete-task
 * Marks a practice assignment task as completed, enforcing 20 XP daily cap and awarding +3 XP.
 */
exports.completeTask = async (req, res) => {
    try {
        const userId = req.userId || req.user?._id || req.user?.uid || req.query?.userId || req.body?.userId
        const { userHobbyId, hobbySkillId, taskId, taskTitle } = req.body

        if (!userHobbyId || !taskId) {
            return sendResponse(res, 400, { success: false, message: 'Missing userHobbyId or taskId.' })
        }

        const UserSkill = require('../Models/UserSkill')
        let userSkill = null
        if (hobbySkillId) {
            userSkill = await UserSkill.findOne({ userHobbyId, hobbySkillId })
        } else {
            userSkill = await UserSkill.findOne({ userHobbyId }).sort({ updatedAt: -1 })
        }

        // Daily Cap Pacing Logic
        const todayStr = new Date().toISOString().split('T')[0]
        const lastDateStr = userSkill?.lastXpDate ? new Date(userSkill.lastXpDate).toISOString().split('T')[0] : ''

        let dailyXp = userSkill?.dailyXpEarned || 0
        if (lastDateStr !== todayStr) {
            dailyXp = 0
        }

        const DAILY_CAP = 20
        const baseXP = 3 // +3 XP per completed practice assignment
        const remainingCap = Math.max(0, DAILY_CAP - dailyXp)
        const xpToAward = Math.min(baseXP, remainingCap)

        let newScore = userSkill?.score || 0
        let newLevel = userSkill?.level || SKILL_LEVEL.BEGINNER

        if (userSkill && xpToAward > 0) {
            newScore = Math.min(100, (userSkill.score || 0) + xpToAward)
            userSkill.score = newScore
            userSkill.dailyXpEarned = dailyXp + xpToAward
            userSkill.lastXpDate = new Date()

            if (newScore >= 76) newLevel = SKILL_LEVEL.EXPERT
            else if (newScore >= 51) newLevel = SKILL_LEVEL.ADVANCED
            else if (newScore >= 26) newLevel = SKILL_LEVEL.INTERMEDIATE
            else newLevel = SKILL_LEVEL.BEGINNER

            userSkill.level = newLevel
            await userSkill.save()
        }

        // Record Practice Session (+5 mins credit for completed practice task)
        await recordLearningPracticeSession({
            userId,
            userHobbyId,
            topicTitle: taskTitle || 'Practice Task Assignment',
            explicitSeconds: 300
        }).catch(() => {})

        return sendResponse(res, 200, {
            success: true,
            message: `Practice task "${taskTitle || taskId}" completed!`,
            xpAwarded: xpToAward,
            newScore,
            newLevel,
            dailyXpEarned: dailyXp + xpToAward,
            isCapReached: (dailyXp + xpToAward) >= DAILY_CAP
        })
    } catch (err) {
        console.error('[SkillLearning] Error in completeTask:', err)
        return sendResponse(res, 500, { success: false, message: 'Failed to complete practice task.', error: err.message })
    }
}

